/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_verovio(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_verovio(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_verovio(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


#include <string>


    #include "../../include/vrv/toolkit.h"
    
    using namespace vrv;
    using namespace std;


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_MussilafNotationfVerovio_new_Toolkit__SWIG_0___(unsigned int jarg1) {
  void * jresult ;
  bool arg1 ;
  vrv::Toolkit *result = 0 ;
  
  arg1 = jarg1 ? true : false; 
  result = (vrv::Toolkit *)new vrv::Toolkit(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MussilafNotationfVerovio_new_Toolkit__SWIG_1___() {
  void * jresult ;
  vrv::Toolkit *result = 0 ;
  
  result = (vrv::Toolkit *)new vrv::Toolkit();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MussilafNotationfVerovio_delete_Toolkit___(void * jarg1) {
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  delete arg1;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetUuid___(void * jarg1) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (arg1)->GetUuid();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetOptions__SWIG_0___(void * jarg1) {
  void * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  Options *result = 0 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (Options *)(arg1)->GetOptions();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SetResourcePath___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->SetResourcePath((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_LoadFile___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->LoadFile((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_LoadData___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->LoadData((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SaveFile___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->SaveFile((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetOptions__SWIG_1___(void * jarg1, unsigned int jarg2) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  bool arg2 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = jarg2 ? true : false; 
  result = ((vrv::Toolkit const *)arg1)->GetOptions(arg2);
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetAvailableOptions___(void * jarg1) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = ((vrv::Toolkit const *)arg1)->GetAvailableOptions();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SetOptions___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->SetOptions((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetOption__SWIG_0___(void * jarg1, char * jarg2, unsigned int jarg3) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool arg3 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  arg3 = jarg3 ? true : false; 
  result = ((vrv::Toolkit const *)arg1)->GetOption((std::string const &)*arg2,arg3);
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetOption__SWIG_1___(void * jarg1, char * jarg2) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = ((vrv::Toolkit const *)arg1)->GetOption((std::string const &)*arg2);
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SetOption___(void * jarg1, char * jarg2, char * jarg3) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  std::string *arg3 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  result = (bool)(arg1)->SetOption((std::string const &)*arg2,(std::string const &)*arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_Edit___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->Edit((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetLog___(void * jarg1) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (arg1)->GetLog();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetVersion___(void * jarg1) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (arg1)->GetVersion();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RenderToDeviceContext___(void * jarg1, int jarg2, void * jarg3) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int arg2 ;
  DeviceContext *arg3 = (DeviceContext *) 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (DeviceContext *)jarg3; 
  result = (bool)(arg1)->RenderToDeviceContext(arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RenderToSVG__SWIG_0___(void * jarg1, int jarg2, unsigned int jarg3) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int arg2 ;
  bool arg3 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = jarg3 ? true : false; 
  result = (arg1)->RenderToSVG(arg2,arg3);
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RenderToSVG__SWIG_1___(void * jarg1, int jarg2) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int arg2 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->RenderToSVG(arg2);
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RenderToSVG__SWIG_2___(void * jarg1) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (arg1)->RenderToSVG();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RenderToSVGFile__SWIG_0___(void * jarg1, char * jarg2, int jarg3) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  int arg3 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  arg3 = (int)jarg3; 
  result = (bool)(arg1)->RenderToSVGFile((std::string const &)*arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RenderToSVGFile__SWIG_1___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->RenderToSVGFile((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RenderToMIDIFile___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->RenderToMIDIFile((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RenderToMIDI___(void * jarg1) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (arg1)->RenderToMIDI();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RenderToTimemap___(void * jarg1) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (arg1)->RenderToTimemap();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RenderToTimemapFile___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->RenderToTimemapFile((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_CreateTimemap___(void * jarg1, unsigned int jarg2) {
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  bool arg2 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->CreateTimemap(arg2);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetHumdrumBuffer___(void * jarg1) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  char *result = 0 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (char *)(arg1)->GetHumdrumBuffer();
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SetHumdrumBuffer___(void * jarg1, char * jarg2) {
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (char *)jarg2; 
  (arg1)->SetHumdrumBuffer((char const *)arg2);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetHumdrumFile___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->GetHumdrumFile((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetHumdrum__SWIG_0___(void * jarg1, void * jarg2) {
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::ostream *arg2 = 0 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (std::ostream *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::ostream & type is null", 0);
    return ;
  } 
  (arg1)->GetHumdrum(*arg2);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetHumdrum__SWIG_1___(void * jarg1) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (arg1)->GetHumdrum();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetElementsAtTime___(void * jarg1, int jarg2) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int arg2 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->GetElementsAtTime(arg2);
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetMEI__SWIG_0___(void * jarg1, int jarg2, unsigned int jarg3) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int arg2 ;
  bool arg3 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = jarg3 ? true : false; 
  result = (arg1)->GetMEI(arg2,arg3);
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetMEI__SWIG_1___(void * jarg1, int jarg2) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int arg2 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->GetMEI(arg2);
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetMEI__SWIG_2___(void * jarg1) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (arg1)->GetMEI();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetElementAttr___(void * jarg1, char * jarg2) {
  char * jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  std::string result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (arg1)->GetElementAttr((std::string const &)*arg2);
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RedoLayout___(void * jarg1) {
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  (arg1)->RedoLayout();
}


SWIGEXPORT void SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_RedoPagePitchPosLayout___(void * jarg1) {
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  (arg1)->RedoPagePitchPosLayout();
}


SWIGEXPORT int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetPageWithElement___(void * jarg1, char * jarg2) {
  int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  int result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (int)(arg1)->GetPageWithElement((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetTimeForElement___(void * jarg1, char * jarg2) {
  int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  int result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (int)(arg1)->GetTimeForElement((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SetScale___(void * jarg1, int jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int arg2 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (int)jarg2; 
  result = (bool)(arg1)->SetScale(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetScale___(void * jarg1) {
  int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (int)(arg1)->GetScale();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SetFormat__SWIG_0___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->SetFormat((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SetFormat__SWIG_1___(void * jarg1, int jarg2) {
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  vrv::FileFormat arg2 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (vrv::FileFormat)jarg2; 
  (arg1)->SetFormat(arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetFormat___(void * jarg1) {
  int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (int)(arg1)->GetFormat();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SetOutputFormat__SWIG_0___(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->SetOutputFormat((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SetOutputFormat__SWIG_1___(void * jarg1, int jarg2) {
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  vrv::FileFormat arg2 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = (vrv::FileFormat)jarg2; 
  (arg1)->SetOutputFormat(arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetOutputFormat___(void * jarg1) {
  int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (int)(arg1)->GetOutputFormat();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_IdentifyInputFormat___(void * jarg1, char * jarg2) {
  int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string *arg2 = 0 ;
  vrv::FileFormat result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (vrv::FileFormat)(arg1)->IdentifyInputFormat((std::string const &)*arg2);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_SetScoreBasedMei___(void * jarg1, unsigned int jarg2) {
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  bool arg2 ;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->SetScoreBasedMei(arg2);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetScoreBasedMei___(void * jarg1) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (bool)(arg1)->GetScoreBasedMei();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_GetPageCount___(void * jarg1) {
  int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  int result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  result = (int)(arg1)->GetPageCount();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_Drag___(void * jarg1, char * jarg2, int jarg3, int jarg4) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string arg2 ;
  int arg3 ;
  int arg4 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg2)->assign(jarg2); 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (bool)(arg1)->Drag(arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_Insert___(void * jarg1, char * jarg2, char * jarg3, char * jarg4) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string arg2 ;
  std::string arg3 ;
  std::string arg4 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg2)->assign(jarg2); 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg3)->assign(jarg3); 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->assign(jarg4); 
  result = (bool)(arg1)->Insert(arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MussilafNotationfVerovio_Toolkit_Set___(void * jarg1, char * jarg2, char * jarg3, char * jarg4) {
  unsigned int jresult ;
  vrv::Toolkit *arg1 = (vrv::Toolkit *) 0 ;
  std::string arg2 ;
  std::string arg3 ;
  std::string arg4 ;
  bool result;
  
  arg1 = (vrv::Toolkit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg2)->assign(jarg2); 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg3)->assign(jarg3); 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->assign(jarg4); 
  result = (bool)(arg1)->Set(arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

